spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://db:3306/facturacion}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
